### ISSUE TITLE
Unable to run

### ISSUE THREAD

**Issue by dmitrySDK** [greenbird/p360-contact-manager#45]
After installing with pip3
> pip3 install p360-contact-manager
...
Successfully installed certifi-2020.11.8 chardet-3.0.4 dependencies-2.0.1 idna-2.10 iso3166-1.0.1 p360-contact-manager-1.0.0 requests-2.25.0 returns-0.14.0 typing-extensions-3.7.4.3 urllib3-1.26.2

Attempt to run fails with following
python3 p360-contact-manager --authkey <VALID AUTH KEY> -pbu <VALID BASE URL> test
/usr/local/bin/python3: can't open file 'p360-contact-manager': [Errno 2] No such file or directory

**Comment by thomasborgen** [comment]
The issue is that we're missing some cli stuff for in the build config.
